import React, { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Clock3, Coffee, Gift, Loader2, PauseCircle, Play, QrCode, Save, UserPlus, Users } from "lucide-react";
import { toast } from "sonner";
import api, { formatApiError } from "@/lib/api";

const input = "mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none focus:border-indigo-400";
const toLocal = (value) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : "";

export default function AdminFreshersCampaignPage() {
  const client = useQueryClient();
  const data = useQuery({ queryKey: ["admin-freshers"], queryFn: async () => (await api.get("/admin/freshers-campaign")).data, refetchInterval: 10000 });
  const [form, setForm] = useState(null);
  const [staff, setStaff] = useState({ name: "", email: "", password: "" });
  const [credentials, setCredentials] = useState([]);
  const campaignData = data.data?.campaign;
  useEffect(() => { if (campaignData && !form) setForm({ ...campaignData, opens_at: toLocal(campaignData.opens_at), closes_at: toLocal(campaignData.closes_at), verification_deadline: toLocal(campaignData.verification_deadline) }); }, [campaignData, form]);
  const save = useMutation({ mutationFn: async (values) => (await api.patch("/admin/freshers-campaign", { ...values, opens_at: new Date(values.opens_at).toISOString(), closes_at: new Date(values.closes_at).toISOString(), verification_deadline: values.verification_deadline ? new Date(values.verification_deadline).toISOString() : null })).data, onSuccess: async () => { toast.success("Campaign settings saved"); await client.invalidateQueries({ queryKey: ["admin-freshers"] }); }, onError: (e) => toast.error(formatApiError(e.response?.data?.detail)) });
  const createStaff = useMutation({ mutationFn: async () => (await api.post("/admin/freshers-campaign/staff", staff)).data, onSuccess: async () => { toast.success("Event staff account created"); setStaff({ name: "", email: "", password: "" }); await client.invalidateQueries({ queryKey: ["admin-freshers"] }); }, onError: (e) => toast.error(formatApiError(e.response?.data?.detail)) });
  const staffStatus = useMutation({ mutationFn: async ({ id, active }) => (await api.patch(`/admin/freshers-campaign/staff/${id}/status`, { active })).data, onSuccess: async () => client.invalidateQueries({ queryKey: ["admin-freshers"] }), onError: (e) => toast.error(formatApiError(e.response?.data?.detail)) });
  const bootstrapStaff = useMutation({ mutationFn: async () => (await api.post("/admin/freshers-campaign/bootstrap-staff")).data, onSuccess: async (result) => { setCredentials(result.credentials); toast.success("Four staff accounts created — save the passwords now"); await client.invalidateQueries({ queryKey: ["admin-freshers"] }); }, onError: (e) => toast.error(formatApiError(e.response?.data?.detail)) });
  const status = useMutation({ mutationFn: async (manual_status) => (await api.patch("/admin/freshers-campaign", { manual_status })).data, onSuccess: async () => client.invalidateQueries({ queryKey: ["admin-freshers"] }), onError: (e) => toast.error(formatApiError(e.response?.data?.detail)) });
  const retryEmails = useMutation({ mutationFn: async () => (await api.post("/admin/freshers-campaign/retry-failed-emails")).data, onSuccess: async (result) => { toast.success(`${result.queued} failed emails queued again`); await client.invalidateQueries({ queryKey: ["admin-freshers"] }); }, onError: (e) => toast.error(formatApiError(e.response?.data?.detail)) });
  if (data.isLoading || !form) return <div className="grid h-96 place-items-center"><Loader2 className="animate-spin text-indigo-300"/></div>;
  const stats = data.data.stats;
  const campaign = data.data.campaign;
  const cards = [
    ["registrations", "Registrations", Users, "text-indigo-300"], ["coupon_reservations", "Café positions", Coffee, "text-amber-300"],
    ["reward_reservations", "Goodies positions", Gift, "text-violet-300"], ["waitlisted", "Waitlisted", Clock3, "text-sky-300"],
    ["unlocked", "Passes unlocked", CheckCircle2, "text-emerald-300"], ["goodies_collected", "Goodies collected", QrCode, "text-teal-300"],
    ["cafe_redeemed", "Café redeemed", Coffee, "text-orange-300"], ["email_sent", "Emails sent", CheckCircle2, "text-sky-300"],
    ["email_pending", "Emails pending", Clock3, "text-amber-200"], ["email_failures", "Email failures", AlertTriangle, "text-rose-300"],
  ];
  return <div><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-indigo-300">Live event control</p><h1 className="mt-2 font-display text-3xl font-black">KIET Freshers 2026</h1><p className="mt-2 text-sm text-zinc-400">Status: <b className="uppercase text-white">{campaign.status}</b> · @kiet.edu only</p></div><div className="flex gap-2"><button onClick={() => status.mutate("paused")} className="inline-flex items-center gap-2 rounded-xl border border-amber-300/20 px-4 py-2.5 text-sm text-amber-200"><PauseCircle size={15}/>Pause</button><button onClick={() => status.mutate("scheduled")} className="inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-4 py-2.5 text-sm font-black text-emerald-950"><Play size={15}/>Resume</button><button onClick={() => status.mutate("closed")} className="rounded-xl border border-rose-300/20 px-4 py-2.5 text-sm text-rose-200">Close now</button></div></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([key, label, Icon, colour]) => <div key={key} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><Icon className={colour} size={18}/><p className="mt-4 text-xs text-zinc-500">{label}</p><p className="mt-1 font-display text-3xl font-black">{stats[key] ?? 0}</p>{key === "email_failures" && stats[key] > 0 && <button onClick={() => retryEmails.mutate()} className="mt-3 text-xs font-bold text-rose-200 underline">Retry failures</button>}</div>)}</div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><h2 className="font-display text-xl font-black">Campaign configuration</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs text-zinc-400">Opens at<input type="datetime-local" value={form.opens_at} onChange={(e) => setForm({ ...form, opens_at: e.target.value })} className={input}/></label><label className="text-xs text-zinc-400">Closes at<input type="datetime-local" value={form.closes_at} onChange={(e) => setForm({ ...form, closes_at: e.target.value })} className={input}/></label><label className="text-xs text-zinc-400 sm:col-span-2">Full-verification deadline <span className="text-zinc-600">(leave blank until decided)</span><input type="datetime-local" value={form.verification_deadline || ""} onChange={(e) => setForm({ ...form, verification_deadline: e.target.value })} className={input}/></label><label className="text-xs text-zinc-400">GOG Cafe offer<textarea rows="4" value={form.gog_offer} onChange={(e) => setForm({ ...form, gog_offer: e.target.value })} className={input}/></label><label className="text-xs text-zinc-400">S Cafe offer<textarea rows="4" value={form.s_cafe_offer} onChange={(e) => setForm({ ...form, s_cafe_offer: e.target.value })} className={input}/></label><label className="text-xs text-zinc-400 sm:col-span-2">Goodies description<input value={form.goodies_description} onChange={(e) => setForm({ ...form, goodies_description: e.target.value })} className={input}/></label><label className="text-xs text-zinc-400 sm:col-span-2">Pickup location / instructions<textarea rows="3" value={form.pickup_location} onChange={(e) => setForm({ ...form, pickup_location: e.target.value })} placeholder="Can be added before passes are collected" className={input}/></label><label className="sm:col-span-2 flex items-start gap-3 rounded-2xl border border-amber-300/15 bg-amber-300/[0.06] p-4 text-sm"><input type="checkbox" checked={Boolean(form.rewards_enabled)} onChange={(e) => setForm({ ...form, rewards_enabled: e.target.checked })} className="mt-1"/><span><b>Enable QR issuance</b><span className="mt-1 block text-xs text-amber-100/60">Keep disabled until the GOG 30-coffee allocation is confirmed. Registrations and reservations still continue.</span></span></label></div><button onClick={() => save.mutate(form)} disabled={save.isPending} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-black"><Save size={15}/>Save settings</button></section>
      <section className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><h2 className="font-display text-xl font-black">Add event staff</h2><p className="mt-2 text-xs leading-5 text-zinc-500">This account can only scan and approve KIET goodies passes.</p><button onClick={() => bootstrapStaff.mutate()} disabled={bootstrapStaff.isPending || data.data.staff.length > 0} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-400 py-3 font-black text-indigo-950 disabled:opacity-40"><UserPlus size={16}/>Create named staff roster</button>{credentials.length > 0 && <div className="mt-4 rounded-2xl border border-amber-300/20 bg-amber-300/[0.07] p-4"><b className="text-sm text-amber-100">Save these passwords now</b>{credentials.map((item) => <div key={item.email} className="mt-3 text-xs"><p className="font-bold">{item.name}</p><p className="font-mono text-zinc-300">{item.email}</p><p className="font-mono text-amber-200">{item.password}</p></div>)}</div>}<div className="my-5 border-t border-white/10"/><p className="text-xs text-zinc-500">Or create another staff account manually.</p>{["name", "email", "password"].map((key) => <label key={key} className="mt-4 block text-xs capitalize text-zinc-400">{key}<input type={key === "password" ? "password" : key === "email" ? "email" : "text"} value={staff[key]} onChange={(e) => setStaff({ ...staff, [key]: e.target.value })} className={input}/></label>)}<button onClick={() => createStaff.mutate()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 py-3 font-black"><UserPlus size={16}/>Create custom account</button><div className="mt-5 space-y-2">{data.data.staff.map((item) => <div key={item.id} className="rounded-xl border border-white/10 p-3"><div className="flex justify-between gap-3"><div><b className="text-sm">{item.name}</b><p className="mt-1 text-xs text-zinc-500">{item.email} · {item.collections} collections</p></div><button onClick={() => staffStatus.mutate({ id: item.id, active: !item.active })} className={`h-fit rounded-lg border px-2.5 py-1 text-xs ${item.active ? "border-rose-300/15 text-rose-300" : "border-emerald-300/15 text-emerald-300"}`}>{item.active ? "Disable" : "Enable"}</button></div></div>)}</div></section></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_340px]"><section className="overflow-hidden rounded-3xl border border-white/10"><div className="p-5"><h2 className="font-display text-xl font-black">Recent participants</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-y border-white/10 bg-white/[0.03] text-xs uppercase text-zinc-500"><tr><th className="p-4">Position</th><th className="p-4">Student</th><th className="p-4">Tier</th><th className="p-4">Status</th><th className="p-4">Goodies</th><th className="p-4">Café</th></tr></thead><tbody>{data.data.recent.map((item) => <tr key={item.id} className="border-b border-white/[0.06]"><td className="p-4 font-mono">#{item.position}</td><td className="p-4"><b>{item.name}</b><p className="text-xs text-zinc-500">{item.email}</p></td><td className="p-4 text-zinc-400">{item.tier?.replaceAll("_", " ")}</td><td className="p-4">{item.status}</td><td className="p-4">{item.goodies_status || "—"}</td><td className="p-4">{item.cafe_name ? `${item.cafe_name} · ${item.cafe_status || "locked"}` : "—"}</td></tr>)}</tbody></table></div></section><aside className="rounded-3xl border border-white/10 bg-white/[0.025] p-5"><h2 className="font-display text-xl font-black">Live scan activity</h2><div className="mt-4 space-y-3">{data.data.activity?.length ? data.data.activity.map((item) => <div key={item.id} className="border-b border-white/[0.07] pb-3 text-sm"><div className="flex items-center justify-between gap-2"><b>#{item.position} {item.student_name}</b><span className={item.result === "duplicate" ? "text-rose-300" : "text-emerald-300"}>{item.result}</span></div><p className="mt-1 text-xs text-zinc-500">{item.kind} · {item.staff_name || "Admin"} · {new Date(item.created_at).toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata" })}</p></div>) : <p className="text-sm text-zinc-500">No scans yet.</p>}</div></aside></div>
  </div>;
}
